version: 0.0
os: linux
files:
  - source: spring-boot-hello-world-example/target/spring-boot-hello-world-example-1.0-SNAPSHOT.war
    destination: /tmp
hooks:
  AfterInstall:
    - location: aws/scripts/after-install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: aws/scripts/application-start.sh
      timeout: 300
      runas: root
  ValidateService:
    - location: aws/scripts/validate-service.sh
      timeout: 300
      runas: root
