name: Build and Deploy

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          aws-region: us-east-1

      - name: Build with Maven
        run: mvn -B package --file spring-boot-hello-world-example/pom.xml

      - name: Upload artifact to S3
        run: |
          aws s3 cp spring-boot-hello-world-example/target/spring-boot-hello-world-example-1.0-SNAPSHOT.war \
          s3://codedeploystack-webappdeploymentbucket-seqdgxfeq2qg/
          
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.IAMROLE_GITHUB }}
          aws-region: us-east-1

      - name: Deploy with CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name CodeDeployAppNameWithASG \
            --deployment-group-name CodeDeployGroupName \
            --s3-location bucket=codedeploystack-webappdeploymentbucket-seqdgxfeq2qg,bundleType=war,key=spring-boot-hello-world-example-1.0-SNAPSHOT.war
